### ISSUE TITLE
Unknown Error related to Slimefun. 

### ISSUE THREAD

**Issue by EchocallingEarth** [baked-libs/dough#227] opened 2023-10-14 18:48 UTC
Referred here by the Slimefun Discord
Referred to Slimefun Discord by PlotsSquared Discord - _**Note they stated it looks like an outdated api version being used by Slimefun.**_

## Description (Required)
When using Slimefun and PlotsSquared I find an error occurs in console. I believe it coincides with entering worlds that have slimefun disabled in them. However, this is only what I noticed while trying to gather info for this bug report.

## Steps to reproduce the Issue (Required)
Install slimefun and PlotsSquared (Latest versions of both are what I used so I recommend this when attempting to reproduce it.

## Expected behavior (Required)
No errors in console or elsewhere

## Server Log / Error Report
https://pastebin.com/nicLKeEc

## Server specs (Required)
Purpur build 2078
Hosted by APEX Hosting

 - Server Software:
 - Minecraft Version: 1.20.2

## FULL plugins list (Required)
Bukkit Plugins: (84):
 AdvancedClaimGuardian, ArmoredElytra, AureliumSkills, Bank, BetterConcrete, BetterLogStrip, BetterPortals, BetterTridents, BigDoors, BlockEffects, BlockProt, BlueMap, ccNoEnderpearlDamage, ChestSort, Chunky, ChunkyBorder, Citizens, ClearFog, CMI, CMIEInjector, CMILib, CommandDefender, ConsoleSay, ConsoleSpamFix, Core, CraftBook, CustomCrafting, DecentHolograms, DisplayShops, DoorsReloaded, dtlTradersPlus, DyedBackpacks, EpicBackpacks, ExecutableBlocks, ExecutableItems, ExoticGarden, ExtraGear, ExtraTools, FastAsyncWorldEdit, GadgetsMenu, HeadDatabase, ImageFrame, InteractiveBoard, ItemsAdder, ItemsAdder-WorldEdit, Jobs, LibsDisguises, LightCleaner, LoneLibs, Lootin, PhatLoots, PlaceholderAPI, PlotSquared, ProtocolLib, PublicCrafters, RealisticSeasons, RealisticVillagers, Redye, SCore, SepareWorldItems, Wailat, WorldEditSelectionVisualizer, WorldGuard, xaero-map-spigot

##Additional info if it will help as taken using the command sf versions.
[Multicraft] EchocallingEarth ran command: sf version
[Server] INFO This Server uses the following setup of Slimefun:
[Server] INFO Purpur git-Purpur-2078 (MC: 1.20.2)
[Server] INFO Slimefun DEV - 1104 (git c977454e)
[Server] INFO Metrics-Module #29
[Server] INFO Java 17
[Server] INFO Installed Addons: (8)
[Server] INFO DyedBackpacks vDEV - 17 (git 8b329e96)
[Server] INFO AureliumSkills vBeta 1.3.23
[Server] INFO ExtraTools vDEV - 36 (git 922c0324)
[Server] INFO ntdLuckyBlock v2.8.12
[Server] INFO ExtraGear vDEV - 13 (git c62047e2)
[Server] INFO CMI v9.6.6.0
[Server] INFO ItemsAdder v3.6.1-beta
[Server] INFO ExoticGarden vDEV - 78 (git 7f9a5f63)

Any additional information I can provide please feel free to reach out to me here or via discord Username: echocallingearth (discord ID# 297596704935378945) Thank you in advance for your help with this matter.

**Comment by EchocallingEarth** [comment] 2023-11-01 03:42
Is anyone actually maintaining this project?

**Comment by TheBusyBiscuit** [comment] 2023-11-02 12:17
Duplicate of #218

**Closed by TheBusyBiscuit** 2023-11-02 12:17 UTC
